version: "3"
volumes:
  mysqldata:
  composer-cache:
    external: true

services:
  mumble_mysql:
    image: mysql:latest
    restart: always
    container_name: ${CONTAINER_MYSQL_DB}    
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
#      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${CONTAINER_PHP}
    restart: always    
    depends_on:
      - mumble_mysql
    volumes:
      - ./:/project
      - composer-cache:/tmp/composer
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-"PUSHTOTALK"}
      - MYSQL_HOST=mumble_mysql
      - MYSQL_USER=${MYSQL_USER:-"PTT_NBILITY"}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-"PTT@31"}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_MYSQL_PHPMYADMIN}
    environment:
#     Si on active PMA_ARBITRARY a 1 cela permet d'avoir le champ server pour indiquer une adresse
#     - PMA_ARBITRARY=1
     - PMA_HOST=mumble_mysql
     - PMA_PORT=3306
#     - PMA_USER=pushtotalk
#     - PMA_PASSWORD=PTT@31
     - VIRTUAL_HOST= ${DOMAINS_PHPMYADMIN}
     - LETSENCRYPT_HOST= ${DOMAINS_PHPMYADMIN}
     - LETSENCRYPT_EMAIL= ${LETSENCRYPT_EMAIL}
    restart: always
    ports:
     - 5269:80
    links:
     - mumble_mysql
    depends_on:
     - mumble_mysql
    volumes:
     - ./sessions

networks:
    default:
      external:
        name: webproxy
